server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.135.0.233:3306/mall?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: Abc123
  redis:
    host: 8.135.0.233
    port: 6379
    database: 0
    password:
  kafka:
    bootstrap-servers: 8.135.0.233:9092
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      properties:
        linger:
          ms: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      properties:
        group:
          id: defaultConsumerGroup
        session:
          timeout:
            ms: 120000
        request:
          timeout:
            ms: 180000
      enable-auto-commit: true
      auto:
        commit:
          interval:
            ms: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: LJBz67RkRq6JeEsRCOd7j1qIINqbuMwutkIYaZdK8lxNRk0218vedNY7UFNtwGNt
  expiration: 3600

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


system:
  id:
    workerId: 1
    datacenterId: 1

