server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

jwt:
  secret: secret
  expiration: 3600

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

system:
  id:
    workerId: 1
    datacenterId: 1