server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.135.0.233:3306/mall?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Abc123

jwt:
  secret: secret
  expiration: 3600

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


system:
  id:
    workerId: 1
    datacenterId: 1